# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:
    inputs:
      secret_gateway_link:
        type: string
        description: GatewayLink
        required: true
      
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        env:
          GATEWAY_PLUGIN_PATH: ../../components/ide/jetbrains/gateway-plugin/build/distributions/gitpod-gateway-test.zip
          GATEWAY_LINK1: ${{ github.events.inputs.secret_gateway_link }}
        run: |
          export GATEWAY_LINK=$(jq -r '.inputs.secret_gateway_link' $GITHUB_EVENT_PATH)
          echo $GATEWAY_LINK
          echo HHHHHHHHHHHH
